fixing regex

diff --git a/.github/workflows/pr-title-check.yml b/.github/workflows/pr-title-check.yml
--- a/.github/workflows/pr-title-check.yml
+++ b/.github/workflows/pr-title-check.yml
@@ -16,9 +16,9 @@ jobs:
         env:
           PR_TITLE: "${{ github.event.pull_request.title }}"
         run: |
-          if [[ "$PR_TITLE" =~ ^(MAJOR|MINOR|PATCH)-.+ ]]; then
+          if [[ "$PR_TITLE" =~ ^\[(MAJOR|MINOR|PATCH)\][[:space:]].+ ]]; then
             echo "PR title matches required format: $PR_TITLE"
           else
-            echo "::error::Pull request title must match 'MAJOR|MINOR|PATCH-<description>'." >&2
+            echo "::error::Pull request title must match '[MAJOR|MINOR|PATCH] <description>'." >&2
             exit 1
           fi
