updating regex

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -41,12 +41,12 @@ jobs:
         env:
           PR_TITLE: "${{ github.event.pull_request.title }}"
         run: |
-          if [[ "$PR_TITLE" =~ ^(MAJOR|MINOR|PATCH)\s(.+) ]]; then
+          if [[ "$PR_TITLE" =~ ^(MAJOR|MINOR|PATCH)[[:space:]]+(.+) ]]; then
             TYPE="${BASH_REMATCH[1]}"
             TYPE=$(echo "$TYPE" | tr '[:upper:]' '[:lower:]')
             echo "type=$TYPE" >> "$GITHUB_OUTPUT"
           else
-            echo "::error::Pull request title must match '[MAJOR|MINOR|PATCH] <description>'" >&2
+            echo "::error::Pull request title must match 'MAJOR|MINOR|PATCH <description>'" >&2
             exit 1
           fi
 
